// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.21.12
// source: notification/v1/notification.proto

package notificationv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	NotificationService_NotifyUserCreated_FullMethodName    = "/notification.v1.NotificationService/NotifyUserCreated"
	NotificationService_NotifyDocumentExpiry_FullMethodName = "/notification.v1.NotificationService/NotifyDocumentExpiry"
)

// NotificationServiceClient is the client API for NotificationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// NotificationService handles notifications for various events
type NotificationServiceClient interface {
	// NotifyUserCreated is called when a new user is created
	NotifyUserCreated(ctx context.Context, in *UserCreatedRequest, opts ...grpc.CallOption) (*UserCreatedResponse, error)
	// NotifyDocumentExpiry is called when a document is about to expire or has expired
	NotifyDocumentExpiry(ctx context.Context, in *DocumentExpiryRequest, opts ...grpc.CallOption) (*DocumentExpiryResponse, error)
}

type notificationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewNotificationServiceClient(cc grpc.ClientConnInterface) NotificationServiceClient {
	return &notificationServiceClient{cc}
}

func (c *notificationServiceClient) NotifyUserCreated(ctx context.Context, in *UserCreatedRequest, opts ...grpc.CallOption) (*UserCreatedResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserCreatedResponse)
	err := c.cc.Invoke(ctx, NotificationService_NotifyUserCreated_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notificationServiceClient) NotifyDocumentExpiry(ctx context.Context, in *DocumentExpiryRequest, opts ...grpc.CallOption) (*DocumentExpiryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DocumentExpiryResponse)
	err := c.cc.Invoke(ctx, NotificationService_NotifyDocumentExpiry_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NotificationServiceServer is the server API for NotificationService service.
// All implementations must embed UnimplementedNotificationServiceServer
// for forward compatibility.
//
// NotificationService handles notifications for various events
type NotificationServiceServer interface {
	// NotifyUserCreated is called when a new user is created
	NotifyUserCreated(context.Context, *UserCreatedRequest) (*UserCreatedResponse, error)
	// NotifyDocumentExpiry is called when a document is about to expire or has expired
	NotifyDocumentExpiry(context.Context, *DocumentExpiryRequest) (*DocumentExpiryResponse, error)
	mustEmbedUnimplementedNotificationServiceServer()
}

// UnimplementedNotificationServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNotificationServiceServer struct{}

func (UnimplementedNotificationServiceServer) NotifyUserCreated(context.Context, *UserCreatedRequest) (*UserCreatedResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method NotifyUserCreated not implemented")
}
func (UnimplementedNotificationServiceServer) NotifyDocumentExpiry(context.Context, *DocumentExpiryRequest) (*DocumentExpiryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method NotifyDocumentExpiry not implemented")
}
func (UnimplementedNotificationServiceServer) mustEmbedUnimplementedNotificationServiceServer() {}
func (UnimplementedNotificationServiceServer) testEmbeddedByValue()                             {}

// UnsafeNotificationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NotificationServiceServer will
// result in compilation errors.
type UnsafeNotificationServiceServer interface {
	mustEmbedUnimplementedNotificationServiceServer()
}

func RegisterNotificationServiceServer(s grpc.ServiceRegistrar, srv NotificationServiceServer) {
	// If the following call panics, it indicates UnimplementedNotificationServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NotificationService_ServiceDesc, srv)
}

func _NotificationService_NotifyUserCreated_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserCreatedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationServiceServer).NotifyUserCreated(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotificationService_NotifyUserCreated_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationServiceServer).NotifyUserCreated(ctx, req.(*UserCreatedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotificationService_NotifyDocumentExpiry_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DocumentExpiryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationServiceServer).NotifyDocumentExpiry(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotificationService_NotifyDocumentExpiry_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationServiceServer).NotifyDocumentExpiry(ctx, req.(*DocumentExpiryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// NotificationService_ServiceDesc is the grpc.ServiceDesc for NotificationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NotificationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "notification.v1.NotificationService",
	HandlerType: (*NotificationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "NotifyUserCreated",
			Handler:    _NotificationService_NotifyUserCreated_Handler,
		},
		{
			MethodName: "NotifyDocumentExpiry",
			Handler:    _NotificationService_NotifyDocumentExpiry_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "notification/v1/notification.proto",
}
